### ISSUE TITLE
Need a way to explicitly set inp_std='No' in ncremap

### ISSUE THREAD

**Issue by xylar** [nco/nco#122]
As noted in the documentation for for [ncclimo](http://nco.sourceforge.net/nco.html#ncclimo-netCDF-Climatology-Generator): 

> In some other non-interactive environments (e.g., crontab, nohup), ncclimo may mistakenly expect input to be provided on stdin simply because the environment is using stdin for other purposes. In such cases users may persuade ncclimo to ignore stdin by explicitly invoking the ‘--clm_md’ option (described above).

...

> Explicitly specifying ‘--clm_md=mth’ serves a secondary purpose, namely invoking the default setting on systems that control stdin. When ncclimo detects that stdin is not attached to the terminal (keyboard) it automatically expects a list of files on stdin. Some environments, however, hijack stdin for their purposes and thereby confuse ncclimo into expecting a list argument. Users have encountered this issue when attempting to run ncclimo in Python parallel environments, via inclusion in crontab, and in nohup-mode (whatever that is!). In such cases, explicitly specify ‘--clm_md=mth’ (or ann or day) to persuade ncclimo to run a normal climatology.

There seems to be no similar option to disable the use of `stdin` for `ncremap`, which makes it impossible to test `ncremap` in both Azure and Circle-CI (which apparently use `stdin` or other purposes).

**Comment by xylar** [comment]
This seems to be the cause of our inability to test `ncremap` in the conda recipe: https://github.com/conda-forge/nco-feedstock/issues/87

**Comment by czender** [comment]
Xylar your diagnosis looks correct, and I will add  the equivalent of a --no_stdin option to ncremap for use in environments that use stdin for other purposes.

**Comment by xylar** [comment]
Okay, great!  That sounds like a good plan.

**Comment by czender** [comment]
The current snapshot of `ncremap` has a new flag, `--no_stdin`, that disables checking `stdin` for input files. This is a flag that takes no argument, not a key-value option. Add `--no_stdin` to any command that might run in an environment, like azure, where `stdin` is used for other purposes. I waffled between this approach and changing the existing `--stdin` flag to a key/value option that could be set to `Yes` or `No`. It would not be hard to do it that way, yet I thought that would be more susceptible to mis-understanding, and somewhat backwards-incompatible. Anyway, if you can test this @xylar please do. Feedback welcome.

**Comment by xylar** [comment]
Thanks @czender! I will try doing a throwaway pull request with the current master to nco-feedstock and see how that goes.

**Comment by xylar** [comment]
Testing here: https://github.com/conda-forge/nco-feedstock/pull/89

**Comment by xylar** [comment]
@czender, the tests succeed under OSX and linux!  I'm going to close this issue and other related ones.

However(!) the Windows build is failing with the same issue (I think): 
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=28414
that you're seeing here in Appveyor on this repo:
https://ci.appveyor.com/project/czender/nco/builds/23845811
It would be really good to get that figured out before doing a 4.8.0 release or the Windows build will be broken once again.  Having no expertise in Windows whatsoever, I can't help there.
