### ISSUE TITLE
Windows build failing for 4.8.0

### ISSUE THREAD

**Issue by xylar** [nco/nco#123]
The Windows build of 4.8.0 (current master) is failing with the same issue (I think) in a conda-forge test: 
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=28414
and in this repo in Appveyor:
https://ci.appveyor.com/project/czender/nco/builds/23845811
It would be really good to get that figured out before doing a 4.8.0 release or the Windows build will be broken once again.  Having no expertise in Windows whatsoever, I can't help there.

**Comment by czender** [comment]
I agree the AppVeyor builds you point to are failing. I think (though am not sure) that Windows failure will go away if we move to netCDF 4.6.3. However, I'm confused because the dashboard version of Appveyor here says "passing":

https://github.com/conda-forge/nco-feedstock

Why does the conda-forge feedstock badge say Passing yet the appveyor builds in my repository fails?

**Comment by xylar** [comment]
>  I'm confused because the dashboard version of Appveyor here says "passing"

That's because everything is fine for v4.7.9 and that's the latest version on conda-forge.  I just did a test PR for 4.8.0-alpha08 (or rather `master` at that time) and that's what failed the Windows build.  This repo also shows failures.

> Why does the conda-forge feedstock badge say Passing yet the appveyor builds in my repository fails?

conda-forge will only update when you do a version release (not an alpha release) so we haven't updated since v4.7.9.  You really need to keep an eye on Appveyor on your own repo.  Which is why I would recommend doing pull request rather than pushing commits directly to master, because only then do you actually get feedback from CI to tell you that a given commit is breaking your build.  I know that's not your habit, but CI isn't very helpful when you don't really watch for when it breaks...

**Comment by czender** [comment]
Thank you for explaining this again and patiently. One of these days I will learn this lesson.
