### ISSUE TITLE
ncpdq: pack and permute at the same time

### ISSUE THREAD

**Issue by adrfantini** [nco/nco#138]
If I am not mistaken, `ncpdq` does not allow to pack variables and permute dimensions at the same time. If `-a` is specified, the variables are not packed, even if explicitly indicated with `-P` or `-M`.

Is this due to a technical limitation? I do not see otherwise the point in keeping these two different tasks available in the same command, if they cannot be executed concurrently.

Running `NCO netCDF Operators version 4.7.9`

**Comment by czender** [comment]
You are not mistaken. The decision to combine them into one operator was made long ago. I cannot remember the overriding justification. We would welcome a patch that makes both permutation and packing possible with a single invocation. It's simply a matter of developer time.

**Comment by adrfantini** [comment]
I do not have the skill nor the time unfortunately. Maybe for the time being a comment in the docs could be added about this, if it is not there already (I did not find it at least).

**Comment by czender** [comment]
Done http://nco.sf.net/nco.html#ncpdq
