### ISSUE TITLE
Normalisation setting in SCRIP generated remap files

### ISSUE THREAD

**Issue by craigmaclachlan** [nco/nco#145]
When SCRIP is used to create bilinear remapping files, the normalisation method is set to "none". Looking at the code, you can see that "norm_opt" is not used in [remap_bilinear.f](https://github.com/SCRIP-Project/SCRIP/blob/master/SCRIP/source/remap_bilinear.f). The current version of ncks [doesn't allow the normalisation value to be "none" for any type of remapping](https://github.com/nco/nco/blob/master/src/nco/nco_rgr.c#L2411).

Suggested change is:
`if(nco_rgr_mth_typ == nco_rgr_mth_conservative && 
   nco_rgr_nrm_typ == nco_rgr_nrm_none){ 
ERROR 
} `

**Comment by craigmaclachlan** [comment]
I raised this issue with @czender via email and he made the [change](https://github.com/nco/nco/commit/d080c1f3dfb01138ccc340619c516b6a98923895). Thanks Charlie!

I have tested this and it works as expected.

**Comment by czender** [comment]
Glad it works for you, Craig. Closing issue.
