### ISSUE TITLE
Allow intersection mesh generator to work on grids with no "grid_area" variable

### ISSUE THREAD

**Issue by czender** [nco/nco#147]
`grid_area` and `grid_imask` are occassionally missing from SCRIP grid files. Please modify the NCO intersection grid generator so it does not depend on their presence. When `grid_area` is not present in source and/or destination grids just print a message to that effect, and compute it directly from the input polygons and put that in `area_a` and `area_b`, respectively. When `grid_imask` is not present in source and/or destination grids just assume it is 1 everywhere, and put that in `mask_a` and `mask_b`, respectively. With these changes we should be able to compute this intersection mesh that ERWG has problems with:
`ncremap --dbg=1 --alg_typ=nco --grd_src=${DATA}/grids/SCRIPgrid_1km-merge-10min_HYDRO1K-merge-nomask_c130402.nc --grd_dst=${DATA}/grids/ne512np4_scrip_c20190125.nc --map=${DATA}/maps/map_hydro1k_to_ne512np4_nco.20190601.nc`

**Comment by hmb1** [comment]
@czender 
task completed
