### ISSUE TITLE
NCO weight generator produces broken maps for FV (cap) grids

### ISSUE THREAD

**Issue by czender** [nco/nco#154]
One can demonstrate this by remapping any uniform grid field, e.g., 180x360, to an FV/cap
grid and reading the debugging output where it notes

> "destination fractions frc_dst = dst_frac = frac_b = frc_out contain non-unity elements (maximum deviation from unity of 636.789 exceeds hard-coded (in variable eps_rlt) relative-epsilon threshold of 1e-14 for frc_out[32896] = 637.789)." 

frac_b should be no larger than 1.0! Think of what it means physically.

Also note that the map is diagnosed as regional (it should be global, as ESMF map is). This might in fact be an easier track to start debugging.

`ncremap --rnr=none -D 3 -a nco -s ${DATA}/grids/180x360_SCRIP.20150901.nc -g ${DATA}/grids/129x256_SCRIP.20150901.nc -m ~/map.nc ${DATA}/ne30/rgr/cmip6_180x360_tst.nc ~/foo.nc
`
compare to ESMF results

`ncremap --rnr=none -D 3 -a aave -s ${DATA}/grids/180x360_SCRIP.20150901.nc -g ${DATA}/grids/129x256_SCRIP.20150901.nc -m ~/map.nc ${DATA}/ne30/rgr/cmip6_180x360_tst.nc ~/foo.nc
`
We cannot release NCO 4.8.2 like this.

Please make it your top priority to understand and fix the behavior of cap grids, and add a
regression test to your suite to verify it stays fixed. It seems highly likely that the poles are mis-handled, because the regridded values are nonsense there, yet look reasonable elsewhere.

**Comment by czender** [comment]
Henry, when you think you have made progress or addressed a GitHub issue it is important to add a comment explaining the progress and/or why you closed the issue.

**Comment by hmb1** [comment]
@czender 
This issue has been fixed and is now in master.
