### ISSUE TITLE
GPL code (nco_gsl.{c,h}) cannot be included in a BSD licensed codebase

### ISSUE THREAD

**Issue by sebastic** [nco/nco#177]
The license change from GPL-3 with NCO exception to BSD-3-Clause makes the code unredistributable because it violates the terms of the GPL applied to `nco_gsl.{c,h}`.

You can include BSD-3-Cause code in a GPL licensed project because the terms of the BSD license allow this (the terms of the GPL being a largely a superset of BSD terms), vice versa is not possible because the terms of the GPL are more restrictive than the BSD ones. It effectively makes the entire codebase it's linked into GPL.

The GSL code will need to be re-licensed under the BSD license, or dual licensed to resolve this issue. Or revert the NCO license back to GPL-3 with NCO exception.

**Comment by czender** [comment]
Thanks for the information. It seems I am in a bind. 

`The GSL code will need to be re-licensed under the BSD license, or dual licensed to resolve this issue. Or revert the NCO license back to GPL-3 with NCO exception.`

Can I "dual-license" just `nco_gsl.[ch]` or is it all of GSL that would need to be dual-licensed? And what would the "dual-license" text say (so I can ask the GSL authors for permission to do that)?

**Comment by sebastic** [comment]
All the copyright holders who released the code in `nco_gsl.{c,h}` under the GPL need to agree to relicense or dual-license.

I would suggest the copyright holders to agree to relicense the bits of GLS in those two files under the GPL-3+ or BSD-3-Clause, so the GPL terms can apply to GSL and the BSD terms to NCO. Dual licensing like this allows those incorporating the code to choose the most appropriate license within the wider scope of their project.

Alternatively they can also just change the license from GPL to BSD, that still allows including the code in the GPL licensed GSL without issues, it just makes that code more permissively licensed to enable including it in BSD or MIT licensed projects.

**Comment by czender** [comment]
The original authors of the GPL code in question were unwilling/unable to dual-license their code. The latest NCO snapshot, 4.9.3-alpha05, eliminates all of the GPL code from `nco_gsl.[ch]`. The remaining code in those files implements stub functions that incorporate nothing from GSL. We may re-write those functions someday to recover the lost functionality, but for now everything in libnco is BSD. Does this satisfy the relevant licensing policy of Debian? We would very much like 4.9.3-final to be compliant.

**Comment by sebastic** [comment]
Removing the GPL code should resolve this license issue.
