### ISSUE TITLE
Build error with nco-4.9.2 and Intel compilers on Mac OS

### ISSUE THREAD

**Issue by pnorton-usgs** [nco/nco#178]
(NOTE: I tried posting this originally to the NCO sourceforge developers forum but it didn't seem to work. If this should be posted else where please let me know).

I was building nco-4.9.2 this morning and ran into the following error.

```
nco_ply_lst.c(792): error: "thr_quota_step" must be specified in a variable list at enclosing OpenMP parallel pragma
  #  pragma omp parallel for default(none) private(idx, thr_idx) shared(bDirtyRats, bSort, fnc_nm ,grd_lon_typ, max_nbr_vrl, mem_lst, pl_cnt_in, pl_lst_in, pl_cnt_dbg, pl_lst_dbg, pl_typ, rtree,  stderr, tot_area, tot_nan_cnt, tot_wrp_cnt)
  ^

nco_ply_lst.c(792): error: "thr_quota" must be specified in a variable list at enclosing OpenMP parallel pragma
  #  pragma omp parallel for default(none) private(idx, thr_idx) shared(bDirtyRats, bSort, fnc_nm ,grd_lon_typ, max_nbr_vrl, mem_lst, pl_cnt_in, pl_lst_in, pl_cnt_dbg, pl_lst_dbg, pl_typ, rtree,  stderr, tot_area, tot_nan_cnt, tot_wrp_cnt)
  ^

compilation aborted for nco_ply_lst.c (code 2)
```

I am using Intel compilers version 19.0.5.281 20190816 on Mac OS (v. 10.13.6). I am using openmpi-4.0.0 and netcdf-4.7.3. I took a look at the source code; it appears that thr_quota_step and thr_quota are only read in the parallel scope so I went ahead and added both those variables to the pragma shared section. After that change the code compiled without error.  I figured I would pass this on in case it needs to be changed in your repo or I applied the wrong fix. Let me know if you have any questions.

-parker

**Comment by czender** [comment]
Thank you for reporting this. This OpenMP code block seems to be a bit out-of-date and we do not test on the Intel compiler very often so we missed that in the last few releases. I incorporated your suggestions, made some other updates, and hopefully all is now well for Intel and newer GCC in the master branch. Unfortunately it appears that the GXX_OLD_OPENMP_SHARED_TREATMENT branch is broken because it uses default(none) yet lacks many of the variables in the Intel branch. @hmb1 please fix this.

**Comment by markyoder** [comment]
Thanks for fixing this! I was just logging in to submit a PR and/or bug report on this! Looks like the newer Intel compilers test for a lot of runtime exceptions that were previously ignored.

**Comment by czender** [comment]
I finally obtained an Intel compiler on my Mac. The forthcoming version 4.9.5 works fine with it. Thanks for. your patience everyone.

**Comment by markyoder** [comment]
I am pretty sure I sorted this out. I think it was more the result of tuning up the module scripts (LMOD) to properly define environment variable definitions of the compiler names, and jumping through other hoops to be sure the correct compiler was being called consistently. 
Intel compilers can give measurable, and sometimes significant, performance boosts for some codes, but they can also be squirrelly, particularly when combining with different versions of MPI, and even more particularly with different implementations of tool-chain management (aka, Open HPC). Basically, you have to be very careful that you are getting the right compiler. For example, in our OHPC stack, it appears (and I could be wrong...) that for Intel compiler + OpenMPI or MPICH, the correct compiler command is `mpicc` or `mpicxx`; for Intel + Intel MPI, `mpiicc`, `mpiicxx`.
