### ISSUE TITLE
ncks -V seg faults

### ISSUE THREAD

**Issue by PatNichols** [nco/nco#18]
Hi,
  I am consultant at CISL/NCAR. One of our users has noticed that ncks (nco 4.5.1,nco 4.5.3) will seg fault for some of his files.

./ncks -V -v datesec file.nc
datesec: type NC_INT, 1 dimension, 1 attribute, compressed? no, chunked? no, packed? no
datesec size (RAM) = 1*sizeof(NC_INT) = 1*4 = 4 bytes
datesec dimension 0: time, size = 1 NC_DOUBLE (Record coordinate is time)
datesec attribute 0: long_name, size = 31 NC_CHAR, value = current seconds of current date

time: type NC_DOUBLE, 1 dimension, 4 attributes, compressed? no, chunked? no, packed? no
time size (RAM) = 1*sizeof(NC_DOUBLE) = 1*8 = 8 bytes
time dimension 0: time, size = 1 NC_DOUBLE (Record coordinate is time)
time attribute 0: long_name, size = 4 NC_CHAR, value = time
time attribute 1: units, size = 30 NC_CHAR, value = days since 2006-01-11 00:00:00
time attribute 2: calendar, size = 9 NC_CHAR, value = gregorian
time attribute 3: bounds, size = 9 NC_CHAR, value = time_bnds

time_bnds: type NC_DOUBLE, 2 dimensions, 1 attribute, compressed? no, chunked? no, packed? no
time_bnds size (RAM) = 1*2*sizeof(NC_DOUBLE) = 2*8 = 16 bytes
time_bnds dimension 0: time, size = 1 NC_DOUBLE (Record coordinate is time)
time_bnds dimension 1: nbnd, size = 2 (Non-coordinate dimension)
time_bnds attribute 0: long_name, size = 23 NC_CHAR, value = time interval endpoints

0
ncks(64777,0x7fff7d5f0310) malloc: *** error for object 0x2: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
Note that this is the output from a MAC, it does the same on Linux w/o the helpful message.
The same command without the -V completes without issue. I can send a .nc file for this if need be but github does not like the .nc ending.
Thanks,
Patrick Nichols
pnichols AT the usual ucar email address suffix

**Comment by czender** [comment]
Please send me the file if it is < 1 MB or tell me where it is on yellowstone.

**Comment by PatNichols** [comment]
Hi Charlie,
  The file is in my scratch directory on yellowstone ->
/glade/scratch/pnichols/file.nc
Thank you for working on this,
Pat

**Comment by czender** [comment]
Thanks for reporting this. The fix/patch is now committed and will be in 4.5.4. If you have a chance to test in advance, please post if it works for you.
cz
