### ISSUE TITLE
ncks flags `--json` and `--dt_fmt=3` do not work together

### ISSUE THREAD

**Issue by Ascendzor** [nco/nco#205]
Hello, I am using ncks to extract data, and I am very pleased with how we are able to convert any time dimension type into ISO8601, I think it is wonderful for standardising our time dimensions across multiple models.

But unfortunately there is a bug... If you are reading data as json, and want to change the time data to ISO8601 then the JSON is invalid.

Here are two one-liners that will fetch an example .nc file from unidata.ucar.edu, both examples have the `--json` flag, the difference between them is that one has the `--dt_mt=3` flag, and the other does not.

```ncks -d time,0 -v time --json https://www.unidata.ucar.edu/software/netcdf/examples/tos_O1_2001-2002.nc```
^ Valid JSON in the response.

```ncks -d time,0 -v time --json --dt_fmt=3 https://www.unidata.ucar.edu/software/netcdf/examples/tos_O1_2001-2002.nc```
^ Invalid JSON in the response

I am still new to nco and ncks, please let me know if I am doing something wrong...
Thank you for reading.

**Comment by czender** [comment]
Thank you for this report. A cursory glance at the JSON looks good to me. and reveals no issues. Please describe why the current syntax is incorrect and what needs to change to make it conformant with the spec.  Please be precise.

**Comment by czender** [comment]
Never mind, I think I see what you mean.  The ISO8601 flag was designed for CDL output, not JSON. We can try to make it work with JSON too. @hmb1 does this look doable?

**Comment by hmb1** [comment]
@czender

Have expanded '--cal/--dt_fmt'  options   to '--jsn and --xml'.    
Have put the code in the branch **hmb-fix-ncks-cal**
If you could check the branch that would be grand as there are so many options it makes my head spin.

**Comment by czender** [comment]
@hmb1 if you think it works and passes all regression tests please submit a PR

**Comment by czender** [comment]
@Ascendzor the patch you have dreaming about for the last week is now in master, thanks to @hmb1. Please test if possible, and re-open issue if necessary, otherwise this will be in NCO 4.9.4 in a few weeks.

```
zender@sastrugi:~/nco$ ncks -d time,0 -v time --json --dt_fmt=3 {
  "dimensions": {
    "time": 1,
    "bnds": 2
  },
  "variables": {
    "time": {
      "shape": ["time"],
      "type": "double",
      "attributes": {
        "standard_name": "time",
        "long_name": "time",
        "units": "days since 2001-1-1",
        "axis": "T",
        "calendar": "360_day",
        "bounds": "time_bnds",
        "original_units": "seconds since 2001-1-1"
      },
      "data": ["2001-01-16T00:00:0.000000"]
    },
    "time_bnds": {
      "shape": ["time", "bnds"],
      "type": "double",
      "data": [["2001-01-01T00:00:0.000000", "2001-02-01T00:00:0.000000"]]
    }
  }
}
zender@sastrugi:~/nco$ ncks -d time,0 -v time --xml --dt_fmt=3 
<?xml version="1.0" encoding="UTF-8"?>
<ncml:netcdf xmlns:ncml="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2" location="file:www.unidata.ucar.edu/software/netcdf/examples/tos_O1_2001-2002.nc">
  <ncml:dimension name="bnds" length="2" />
  <ncml:dimension name="time" length="1" isUnlimited="true" />
  <ncml:variable name="time" type="double" shape="time">
    <ncml:attribute name="standard_name" separator="*" value="time" />
    <ncml:attribute name="long_name" separator="*" value="time" />
    <ncml:attribute name="units" separator="*" value="days since 2001-1-1" />
    <ncml:attribute name="axis" value="T" />
    <ncml:attribute name="calendar" separator="*" value="360_day" />
    <ncml:attribute name="bounds" separator="*" value="time_bnds" />
    <ncml:attribute name="original_units" separator="*" value="seconds since 2001-1-1" />
    <ncml:values separator="*">2001-01-16T00:00:0.000000</ncml:values>
  </ncml:variable>
  <ncml:variable name="time_bnds" type="double" shape="time bnds">
    <ncml:values separator="*">2001-01-01T00:00:0.000000*2001-02-01T00:00:0.000000</ncml:values>
  </ncml:variable>
</ncml:netcdf>
```

**Comment by metdockal** [comment]
Hello @czender, thank you for fixing this issue. However, seconds should have two digits in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601#Times). 

From your example above:
"2001-01-01T00:00:0.000000"
valid ISO would be
"2001-01-01T00:00:00.000000"

**Comment by czender** [comment]
Thanks for pointing this out. Reopening issue...

**Comment by czender** [comment]
Please help me understand ISO8601 as I am not a date guru. 
1. Does ISO8601 always use "," (comma)  or "." (decimal point) to separate the integer seconds from the fractional seconds?
https://dencode.com/en/date always uses commas
I wonder if that is a hard and fast rule or depends on LOCALE

**Comment by Ascendzor** [comment]
Aloha @czender,

I think that the is not comma vs decimal point, but rather the number of 0s before the last decimal point.

"2001-01-01T00:00:0.000000"
                                    ^
     There is only 1 zero here for


When I use dencode for now, I get this ISO string `20201026T182352,215Z` which is correct ISO string, comma included.
Here is an example of me ingesting this ISO using luxon a js datetime library.
```luxon.DateTime.fromISO('20201026T182352,215Z').toString()
"2020-10-27T07:23:52.215+13:00"```

**Comment by czender** [comment]
The number of zeros before the last decimal point is fixed in the latest snapshot. I think the comma from "dencode" is related to the LOCALE settings, and can be a decimal point when LOCALE is C. Here is the current output. Would you like any further changes?
```
zender@sastrugi:~/nco$ ncks -d time,0 -v time --dt_fmt=3 --json ~/nco/data/in.nc
{
  "dimensions": {
    "vrt_nbr": 2,
    "time": 1
  },
  "variables": {
    "climatology_bounds": {
      "shape": ["time", "vrt_nbr"],
      "type": "float",
      "attributes": {
        "purpose": "Variable containing CF-compliant climatology bounds for time dimension"
      },
      "data": [["1964-03-13T09:08:16.000000", "1964-03-14T09:08:16.000000"]]
    },
    "time": {
      "shape": ["time"],
      "type": "double",
      "attributes": {
        "long_name": "time",
        "units": "days since 1964-03-12 12:09:00 -9:00",
        "calendar": "gregorian",
        "bounds": "time_bnds",
        "climatology": "climatology_bounds"
      },
      "data": ["1964-03-13T21:09:00.000000"]
    },
    "time_bnds": {
      "shape": ["time", "vrt_nbr"],
      "type": "float",
      "attributes": {
        "purpose": "Cell boundaries for time coordinate"
      },
      "data": [["1964-03-13T09:08:16.000000", "1964-03-14T09:08:16.000000"]]
    }
  }
}
zender@sastrugi:~/nco$ 

```

**Comment by Ascendzor** [comment]
This is perfect,
thank you @czender

**Comment by czender** [comment]
Great, re-closing. This will be in 4.9.6-final in a couple of weeks.
