### ISSUE TITLE
ncks fails to remove a variable

### ISSUE THREAD

**Issue by rkouznetsov** [nco/nco#211]
I want to remove a variable (that is not coordiante in NetCDF sense) form a file [small.nc.gz](https://github.com/nco/nco/files/5062318/small.nc.gz).
` ncks -v longitude -v latitude -x small.nc small1.nc `
ncks silently ignores the request.  Tested with 4.9.4-alpha07.

The workaround was to rename the variables and then remove them.
Looks like nco tries to outsmart a user here. I would expect nco to do what it is instructed to. 

Thank you!

**Comment by czender** [comment]
This is a feature not a bug.
Please read http://nco.sf.net/nco.html#exclude and http://nco.sf.net/nco.html#xcl_ass_var

**Comment by rkouznetsov** [comment]
Thank you! Good to know.  

In this particular case my problem was that the program failed to perform the explicitly requested action  and returned a zero status. 
I believe, that regardless the reason of failure (design concept is also a valid reason) the program should return an error. Ideally, together with a message referring to the feature...
Would it not be a bit more logical behavior?

**Comment by czender** [comment]
Rest assured you are not the first person who has stumbled over this feature. I am always in favor of more informative INFO messages and would welcome a patch indicating that the specified coordinate-like were retained not excluded due to their being associated with other non-excluded variables (i.e., Cloud_Mask). I cannot make doing this a priority personally.

**Comment by rkouznetsov** [comment]
Thanks. At least the policy has been declared somewhere. Here are some personal thoughts, that might (or might not:) be of interest. Please do not take them too seriously.

In this particular case the file does not have any "association" of  Cloud_Mask to longitude and latitude except for sharing same dimensions. It was only the variable name that triggered the disobeyance of ncks.  Latitudes and longitudes occupy 90% of the file size and can be reconstructed from the file metadata and a 1-km elevation map. Therefore removing longitude and latitude them is perfectly legitimate and reasonable operation, if one has limited disk bandwidth and disk space and wants to go through the whole MODIS archive many times.

In my applications nco is usually hidden very deep inside other scripts that launch hundreds of instances in parallel, and INFO is just something that makes logs even bigger. In such applications the only excuse for a human to look into the logs is a crash (non-zero exit code), for which an informative ERROR message should be provided. In my scripts I try to reduce talkativity and history logging, since those quickly become too big to be of any practical use.

I am sorry to learn that nco is on its way from being simple and reliable towards duplicating functionality and unwanted creativity of cdo (which is an excellent tool in the realm of CF-compliant datasets). NetCDF is being used well beyond the GCM world, and I have appreciated the ease to perform low-level netcdf manipulation with nco, which has been a killer-feature for me. Looks like it has not been the case for quite some time already.

**Comment by czender** [comment]
Thank you for your thoughts.
On reconsideration, I agree that users would be better served
by an error when what they explicitly request cannot be
performed without an additional option.
We can add this to the TODO list.
It requires writing a new function to call at about line 6874
of nco_grp_utl.c that checks whether the extraction rules lead 
to retaining user-excluded variables, something like this

`if(EXCLUDE_INPUT_LIST) (void)nco_xtr_xcl_chk(EXTRACT_ASSOCIATED_COORDINATES,var_lst_in,var_xtr_nbr,trv_tbl);
`
What makes that difficult to do exactly right is the possibility
of regular expressions (which are rare) in variable and group names,
and issues associated with excluding variables that can occur with
the same name but multiple groups in netCDF4 files. If one neglects
these complexities, one could probably write this function in a day.

Charlie

**Comment by czender** [comment]
The latest snapshot, NCO. 4.9.4-alpha13 contains this change, i.e., it now dies with an ERROR and HINT.
