### ISSUE TITLE
pip install in Google Colab only have super old version

### ISSUE THREAD

**Issue by yingpublic** [nco/nco#213]
Hi, I'd like to use nco package to concatenate the netCDF file. 
When I tried to install package in Google Colab, I can only get the 1.0.0 version

`!pip install nco`

> Requirement already satisfied: nco in /usr/local/lib/python3.6/dist-packages (1.0.0)

Even if I tried to update the package, I still get the same version.

`!pip install --upgrade nco`

> Requirement already up-to-date: nco in /usr/local/lib/python3.6/dist-packages (1.0.0)

Any idea how to get the latest version? Or any ideas I am missing any requirement? Thank you!

**Comment by czender** [comment]
I do not know what Google Colab is, and we at NCO HQ do not support it, although a volunteer might have done so. I suspect this version 1.0.0 indicates this is PyNCO (which has no version > 1.0) and it is the only version on Colab so upgrades are not available. But so what, as long as the concatenator works for you.

**Comment by czender** [comment]
Unable to reproduce
