### ISSUE TITLE
Option for disabling shuffle needed

### ISSUE THREAD

**Issue by rkouznetsov** [nco/nco#220]
shuffle is not always beneficial for compression.
Attached file after 
` ncks -4 -L9  in.nc4 out.nc4 `
grows by  some 15%. The only difference is that ncks always shuffles variables.

It would be great to have an option to forbid shuffling.
Thank you!

[in.nc4.gz](https://github.com/nco/nco/files/5193893/in.nc4.gz)

**Comment by czender** [comment]
The forthcoming NCO 5.0.8, built on netCDF 4.9.0, exposes the Shuffle filter to user control as described [here](http://nco.sf.net/nco.html#compression). The command above can be expressed as
`ncks -4 --cmp=dns,9 in.nc4 out.nc4`

**Comment by rkouznetsov** [comment]
Great! Thank you!
