### ISSUE TITLE
ncap2 not installed building v4.9.7

### ISSUE THREAD

**Issue by saveriogzz** [nco/nco#231]
Hi!

I built from source **nco v 4.9.7** and it seems that I can correctly call all the commands (ncdpg, ncecat, ecc.) from command line, except for **ncap2**.  
What could have gone wrong?

Cheers

**Comment by czender** [comment]
The most likely thing is that the build system was unable to find all the `ncap2` dependencies (ANTLR, GSL, ...) mentioned on the homepage, so it built/installed everything except `ncap2`.

**Comment by saveriogzz** [comment]
Thanks! Is there any solution you would suggest?

**Comment by saveriogzz** [comment]
Thanks!
I couldn't find the dependencies listing.
Would you suggest a solution for it? Like installing the dependencies and again install nco from source?

Cheers

**Comment by czender** [comment]
Instructions are on the [homepage](http://nco.sf.net#bld)
