### ISSUE TITLE
ERROR nco_err_exit() with ncrcat -h  

### ISSUE THREAD

**Issue by DiegoGutierrez2210** [nco/nco#232]
Hi everyone

I tried to concatenate with ncrcat 18 files, but I got this error:

-----------
Code in ubuntu terminal:
ncrcat -h ww3.boya_puy_1989_spec1.nc ww3.boya_puy_1989_spec2.nc ww3.boya_puy_1990_spec1.nc ww3.boya_puy_1990_spec2.nc ww3.boya_puy_1991_spec1.nc ww3.boya_puy_1991_spec2.nc ww3.boya_puy_1992_spec1.nc ww3.boya_puy_1992_spec2.nc ww3.boya_puy_1993_spec1.nc ww3.boya_puy_1993_spec2.nc ww3.boya_puy_1994_spec1.nc ww3.boya_puy_1994_spec2.nc ww3.boya_puy_1995_spec1.nc ww3.boya_puy_1995_spec2.nc ww3.boya_puy_1996_spec1.nc ww3.boya_puy_1996_spec2.nc ww3.boya_puy_1997_spec1.nc ww3.boya_puy_1997_spec2.nc prueba.nc

results:
ncrcat: INFO/WARNING Multi-file concatenator encountered packing attribute scale_factor for variable longitude. NCO copies the packing attributes from the first file to the output file. The packing attributes from the remaining files must match exactly those in the first file or data from subsequent files will not unpack correctly. Be sure all input files share the same packing attributes. If in doubt, unpack (with ncpdq -U) the input files, then concatenate them, then pack the result (with ncpdq). This message is printed only once per invocation.
nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco_get_vara()
nco_err_exit(): ERROR Error code is -101. Translation into English with nc_strerror(-101) is "NetCDF: HDF error"
nco_err_exit(): ERROR NCO will now exit with system call exit(EXIT_FAILURE)
----------

I always use NCO to concatenate these kind of files and it's my firt ERROR with this proceses. Why is it happing now and not before? Any ideas for solve this?

Thanks for any help

Regards

**Comment by czender** [comment]
Hello Diego, 

This is a rather inscrutable error. Many issues could cause it. You might have a corrupt file. See if you can form a simple way to reproduce the problem with fewer, smaller files until you have a command that fails that involves no more than two input files with one variable in them, then we can take a look at it. Also try running with debugging, e.g., "-D 2" as that might provide more information.

cz

**Comment by DiegoGutierrez2210** [comment]
Hello!
Thanks for answer me!
I tried to run with less files, and I did not have any problem until run 12 files (it works just 11 files max). Also, where may I use "-D 2" in my line code?

Regards

**Comment by DiegoGutierrez2210** [comment]
> Hello Diego,
> 
> This is a rather inscrutable error. Many issues could cause it. You might have a corrupt file. See if you can form a simple way to reproduce the problem with fewer, smaller files until you have a command that fails that involves no more than two input files with one variable in them, then we can take a look at it. Also try running with debugging, e.g., "-D 2" as that might provide more information.
> 
> cz

**Comment by DiegoGutierrez2210** [comment]
> > Hello Diego,
> > This is a rather inscrutable error. Many issues could cause it. You might have a corrupt file. See if you can form a simple way to reproduce the problem with fewer, smaller files until you have a command that fails that involves no more than two input files with one variable in them, then we can take a look at it. Also try running with debugging, e.g., "-D 2" as that might provide more information.
> > cz

**Comment by czender** [comment]
Diego, Unfortunately I cannot help you with corrupt files. You need to obtain working files. It seems you are unfamiliar with reading the NCO manual, which will further explain how to run with `-D 2`. Please try to read and understand the examples in the manual before posting againg.
