### ISSUE TITLE
Doing "ncrename --dimension old,new" does not seem to update dimids in variables.

### ISSUE THREAD

**Issue by bartgol** [nco/nco#236]
Maybe I'm not using/understanding the tool correctly, but I think ncrename is not updating dimensions ids inside variables correctly.

I am not sure how else to express the issue, so I'm going to report some commands and their outputs.

Here's the "initial" nc file:
```
$ ncdump small.nc
netcdf small {
dimensions:
	COL = 3 ;
	LEV = 2 ;
	ILEV = 3 ;
variables:
	double T(COL, LEV) ;

// global attributes:
		:ncol = 3L ;
		:nlev = 2L ;
		:_NCProperties = "version=2,netcdf=4.7.4,hdf5=1.12.0," ;
data:

 T =
  273, 273,
  273, 273,
  273, 273 ;
}
```
Then I change the name `LEV` to `VERT_LEV`:
```
$ ncrename --dimension LEV,VERT_LEV small.nc copy.nc
$ ncdump copy.nc 
netcdf copy {
dimensions:
	COL = 3 ;
	ILEV = 3 ;
	VERT_LEV = 2 ;
variables:
	double T(COL, VERT_LEV) ;

// global attributes:
		:ncol = 3L ;
		:nlev = 2L ;
		:_NCProperties = "version=2,netcdf=4.7.4,hdf5=1.12.0," ;
		:history = "Mon Mar  1 21:36:42 2021: ncrename --dimension LEV,VERT_LEV small.nc copy.nc" ;
		:NCO = "netCDF Operators version 4.7.5 (Homepage = http://nco.sf.net, Code = http://github.com/nco/nco)" ;
data:

 T =
  273, 273,
  273, 273,
  273, 273 ;
}

```
Everything seems right, and yet, when using `copy.nc` inside some python code (which uses the [netCDF4 package](https://unidata.github.io/netcdf4-python/#install)) things crash. I put some print statements, and found something interesting:

From opening the "initial" `small.nc` file (using the [dataset](https://unidata.github.io/netcdf4-python/#Dataset) class in netCDF4):
```
opening small.nc
building dataset with grpid=65536
grpid 65536 has 3 dims
  dim[0]: name=COL, id=0
  dim[1]: name=LEV, id=1
  dim[2]: name=ILEV, id=2
found 1 vars
processing var 0
  name: T
  ndims: 2
  dimids[0] = 0
  dimids[1] = 1
```
but when opening `copy.nc`:
```
opening copy.nc
building dataset with grpid=131072
grpid 131072 has 3 dims
  dim[0]: name=COL, id=0
  dim[1]: name=ILEV, id=2
  dim[2]: name=VERT_LEV, id=3
found 1 vars
processing var 0
  name: T
  ndims: 2
  dimids[0] = 0
  dimids[1] = 1
```
So you can see that `LEV` has correctly disappeared, and the new dim `VERT_LEV` has been added, with a _new_ dim id (3). However, the id of the dimensions in the stored variable has not changed: 0 and 1. So when later the dimension with id 1 is searched in copy.nc, nothing is found, and this eventually leads to a crash.

My question is: is this the intended behavior? Am I supposed to 'update' the dim ids in the variables manually somehow? Or is this a bug? Or maybe I'm not using the tool correctly?

For context, I installed NCO with pip3 on a RHEL7 machine.
```
$ ncrename --version
NCO netCDF Operators version 4.7.5 built by mockbuild on nowhere at Jun 20 2018 02:49:50
ncrename version 4.7.5
```

Thank you for reading this far!

**Comment by czender** [comment]
Nearly, if not completely, all issues ever reported with `ncrename` boil down to https://github.com/Unidata/netcdf-c/issues/597. Converting to/from netCDF3 before/after using `ncrename` always fixes the issue. More documentation at http://nco.sf.net/nco.html#bug_nc4_rename. Please re-open this issue if that workaround fails for you.

**Comment by bartgol** [comment]
@czender Ah, I stumbled on that issue, but it was very long, and I guess I missed that bit. The tric `4to3->rename->3to4` works for me too. Thanks!
