### ISSUE TITLE
NCKS Hyperslabs do not reduce sufficiently file size

### ISSUE THREAD

**Issue by EnlNovius** [nco/nco#247]
nco : 5.0.1
netcdf4 : 1.5.7

Hello,
I'm using ncks to separate an n-day file into n daily files by running n `ncks` commands (using a python script). The script itself does not modify any file, it simply reads the dates before running `ncks` commands to extract each day.
For applying the script to an 11G annual file, I get 365 files for a total of ~11G.
The problem I'm having is on another annual file quite close in data (~17G). Once the script is executed, I get 365 files of ~670 MB, for a total of ~210G (so a x10 in size).

I suspect two causes: data that is not deleted but simply hidden, or metadata. 

Example:

To give an example, I extracted a subfile from my initial file (using ncks):
```
ncks -d latitude,300,320 -d longitude,300,320 -d time,0,20 smos_2010.nc debug.nc
```
This greatly reduces my dimensions:
```
time (UNLIMITED): 657 -> 21
latitude: 741 -> 21  
longitude: 711 -> 21
```
On this extraction I have no problem, I have a significant decrease in the size of my file (17G -> 456K).

Here is the file : [debug.zip](https://github.com/nco/nco/files/7115409/debug.zip)

Now, if I apply my script to this file, (It only executes the following commands), I get 11 files of size 456K, for a total of 5MO (x10).
```shell
ncks --mk_rec_dmn time debug.nc -O debug.nc
Date: 2010-01-15
ncks -h -d time,0,1 debug.nc -O 2010/201001/SMOS_L3SM_20100115.nc
Date: 2010-01-16
ncks -h -d time,2,3 debug.nc -O 2010/201001/SMOS_L3SM_20100116.nc
Date: 2010-01-17
ncks -h -d time,4,5 debug.nc -O 2010/201001/SMOS_L3SM_20100117.nc
Date: 2010-01-18
ncks -h -d time,6,7 debug.nc -O 2010/201001/SMOS_L3SM_20100118.nc
Date: 2010-01-19
ncks -h -d time,8,9 debug.nc -O 2010/201001/SMOS_L3SM_20100119.nc
Date: 2010-01-20
ncks -h -d time,10,11 debug.nc -O 2010/201001/SMOS_L3SM_20100120.nc
Date: 2010-01-21
ncks -h -d time,12,13 debug.nc -O 2010/201001/SMOS_L3SM_20100121.nc
Date: 2010-01-22
ncks -h -d time,14,15 debug.nc -O 2010/201001/SMOS_L3SM_20100122.nc
Date: 2010-01-23
ncks -h -d time,16,17 debug.nc -O 2010/201001/SMOS_L3SM_20100123.nc
Date: 2010-01-24
ncks -h -d time,18,19 debug.nc -O 2010/201001/SMOS_L3SM_20100124.nc
Date: 2010-01-25
ncks -h -d time,20,20 debug.nc -O 2010/201001/SMOS_L3SM_20100125.nc
```

**Comment by czender** [comment]
Any significant difference between your expectations and the actual filesize are most likely due to poor chunk sizes. The netCDF library determines these size automatically. You can override them with NCO options as described [here](http://nco.sf.net/nco.html#cnk). I suggest you consider changes the chunk sizes to those used in the file that worked well for you. This is unlikely to be an NCO issue so I am closing it.

**Comment by EnlNovius** [comment]
It was the good solution, thank you for the help, applying `ncks -O -4 --cnk_map=nc4 in.nc out.nc` reduced the size of output file from 670MO to 37MO. 
By the way, the first link of the documentation 3.31 Chunking : http://www.hdfgroup.org/HDF5/doc/H5.user/Chunking.html
return _Page not found_.

**Comment by czender** [comment]
Glad to hear it!
