### ISSUE TITLE
ncrcat adds erroneous(?) variable attribute

### ISSUE THREAD

**Issue by vanderwb** [nco/nco#262]
I'm working with one of our HPC users at NCAR who reports that recent versions of `ncrcat` add an attribute to variables using the record dimension (time in our case). Please see the following example:

```
$ ncdump -h 1982.nc
...
        float precip(time, lat, lon) ;
                precip:long_name = "gpcc full data daily product version 2018 precipitation per grid" ;
                precip:units = "mm/day" ;
                precip:code = 20 ;
                precip:_FillValue = -9999.f ;
                precip:missing_value = -9999.f ;
...

$ ncrcat 198[2-3].nc result.nc
$ ncdump -h result.nc
...
        float precip(time, lat, lon) ;
                precip:long_name = "gpcc full data daily product version 2018 precipitation per grid" ;
                precip:units = "mm/day" ;
                precip:code = 20 ;
                precip:_FillValue = -9999.f ;
                precip:missing_value = -9999.f ;
                precip:cell_methods = "time: mean" ;
...
```

The `cell_methods = "time: mean"` is the concern here, as we do not expect any "mean" to be taken during the file concatenation. The user has tested the following versions:

```
No attribute added: nco/4.7.4 nco/4.7.9
Attribute is added: nco/4.9.5 nco/5.0.3 nco/5.1.0 nco/5.1.4
```

Let me know if I can provide any other information that would be helpful.

**Comment by czender** [comment]
Thank you for reporting this bug. I just fixed it in the current snapshot that will become NCO 5.1.5 eventually. Until then your user can work around the issue by adding the `--no_cll_mth` switch to their `ncrcat` invocations.
