### ISSUE TITLE
Parallelize compression over chunks?

### ISSUE THREAD

**Issue by mdunphy** [nco/nco#264]
If I understand correctly, nco is threaded (OpenMP) but few operations benefit from threads because most operations are I/O bound. Compression (eg, `ncks -L 1`) is compute bound, but the the compression algorithm doesn't readily parallelize. However, with chunking, it should be possible to compress each chunk using it's own thread and thus grind through the compression in parallel. The memory usage would probably scale with chunksize*numthreads as I suspect each compressed chunk would have to stay in memory during the compression before being written out (perhaps by a dedicated writing thread). Is it plausible to add it to nco/ncks?

**Comment by czender** [comment]
It's possible thought not too plausible. Parallel compression is better supported at the library level. Libraries like Parallel I/O (PIO, which can use the netCDF4-parallel library on parallel filesystems), and BLOSC already support parallel compression. NCO can call BLOSC right now. However, I've yet to see an performance gains from using it.

**Comment by mdunphy** [comment]
OK, thanks for getting back to me. That makes sense to rely on a library here.
