### ISSUE TITLE
ncap2 ignores "--cmp" when new dimensions are defined

### ISSUE THREAD

**Issue by ocehugo** [nco/nco#269]
Hello,
I'm currently facing an unexpected behaviour with ncap2 and compression:

```bash
ncap2 --cmp='dfl' -s 'defdim("time",1,0);mv_var=var.get_miss();var($time,$lon,$lat)=var; var.set_miss(mv_var);' var2d.nc var3d.nc
```

This will properly extend `var`, but the compression flag is ignored and my `var3d.nc` file now blows out in size (`var2d.nc` here is already compressed/nc4/hdf5). Including `"--4"` do not help force the compression either. 

I can call ncks/ncap2 again to compress the final file afterwards, but I would like to keep things neat in a single call and avoid all the overhead. Is anything I'm missing here?

**Comment by czender** [comment]
The intent of your `ncap2` command is unclear to me. However, I was able to reproduce an issue with `ncap2` not compressing new variables. While doing so, I notice that using `-L 1` instead of `--cmp='dfl'` might help. Please LMK if that workaround solves the immediate problem.

Also, `var.set_miss(var2d)` might be causing problems. `set_miss() ` expects a scalar argument for the missing value, not a 2D array.

**Comment by ocehugo** [comment]
Hi @czender ,

Thanks for the quick response. The intent is to transform a 2d array into time record 3d using the same data and applying the mask/missing value. I will revert back to using the `L` flag for ncap2 now and try to fix the fill_missing argument.  Spotted the problem when using new filters. I can't trust my memory but I think the fill_missing call was tthe shortest path to have the array properly broadcasted when I coded ages ago.

**Comment by ocehugo** [comment]
The snippet I typed above was wrong (see edited version now), so I was set/get missing correctly. 

Indeed, using old and tried `-LN` flag will do the compression. However, some burden/overhead by the lacking of that is quite predictable: 
```bash
...
opts="--cmp 'myfavcompression'"
...
ncks $opts ... a.nc b.nc 
#force -L1 or handroll a flag argument conversion (we don't want that...)
ncap2 -L1 -s ... b.nc c.nc #if we end here, compression is not what I asked for.
ncks $opts ... c.nc d.nc #if we got more on the plate, we have a small read-overhead from reading a larger c.nc
```

Not the end of the world, but not optimal either. I assume most users somehow inject/force default arguments to all calls, particularly compression.

**Comment by czender** [comment]
@hmb1 As this thread shows,` ncap2` does not support the `--cmp` option when simultaneously creating new variables (or something like that). I thought I had hooked up the `--cmp` support in all appropriate `ncap2 `subroutines but apparently I missed one. Any idea which one? i.e., where does `ncap2` call `nc_def_var()` without an immediately following call to `nco_flt_def_*`?

**Comment by czender** [comment]
Okay, nevermind. I think I found the locations that I had missed before. There are two in `prs_cls.cc`. I'll add this to the TODO list.

**Comment by czender** [comment]
@ocehugo the latest NCO snapshot includes a fix for the problem you reported. If you can, please test the snapshot and LMK if it works for you. Otherwise it will be in NCO 5.1.6 to be released in a week or two.

**Comment by czender** [comment]
Please reopen if this does not work for you with NCO 5.1.9
