### ISSUE TITLE
using ```ncrename``` generates a corruped file

### ISSUE THREAD

**Issue by jerabaul29** [nco/nco#275]
This is opened following the discussion at:

https://github.com/pydata/xarray/issues/8072

i.e., citing from there:

```python
import os
import xarray as xr
xr.show_versions()
# get the file
!wget https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3Ad5f179a3-76a8-4e4f-b45f-8e8d85960ba6
# rename the file
!mv urn\:uuid\:d5f179a3-76a8-4e4f-b45f-8e8d85960ba6 bar_BSO3_a_rcm7_2008_09.nc
# the file is not xarray-friendly, modify and rename
!ncrename -v six_con,six_con_dim bar_BSO3_a_rcm7_2008_09.nc bar_BSO3_a_rcm7_2008_09_xr.nc
xr.open_dataset("./bar_BSO3_a_rcm7_2008_09_xr.nc")
```

> In any case, ncrename might have created a corrupted file: according to ncdump -h, the all_con dimension appears to have been replaced by another nchar dimension of size 4 (while originally all_con had a size of 67).

There are discussions / we are wondering where the issue comes from, but thought discussing here may help anyways :)

> I don't know a lot about nco, but given that netcdf-python also seems to be affected this might be a bug in netcdf-c. In any case, opening an issue on the nco repository should help figuring out what exactly is going wrong.

**Comment by czender** [comment]
You're using the right command, but it may not
work as intended if the file is netCDF4.
If so, use the workaround described here:
http://nco.sf.net/nco.html#bug_nc4_rename
In summary, the problem is likely with netCDF-C, not NCO.
It is a longstanding problem and Unidata has not mustered
the resources to fix it.
