### ISSUE TITLE
bogus non-monotonicity warning with --record_append

### ISSUE THREAD

**Issue by sethmcg** [nco/nco#288]
I'm getting bogus warnings about intra-file non-monotonicity from `ncrcat` when I use the `--record_append` option.

I have two files that I'm concatenating.  The time coordinate variables in both are well-structured and have identical `time@units` and `time@calendar` attributes.  The values of the time coordinate are regularly spaced and continue monotonically from one file to the next.

If I use `ncrcat -h file1.nc file2.nc result.nc`, everything works as expected.
If I do `cp file1.nc result.nc; ncrcat -h --record_append file2.nc result.nc`, the resulting file is identical to the first case.  BUT, when it runs, for every single timestep it emits a warning message like this:
`ncrcat: WARNING Intra-file non-monotonicity. Record coordinate "time" does not monotonically decrease between (input file file2.nc record indices: 0, 1) (output file result.nc record indices 720, 721) record coordinate values 175680.000000, 175740.000000`

This is especially weird because the coordinate value should be _increasing_, not _decreasing_; I've never run into a case where you'd want the time coordinate to be decreasing as you append to a file.

I found an issue on SourceForge from 2013 that talks about this same warning, and it was reported fixed in v.4.3.1:  https://sourceforge.net/p/nco/discussion/9830/thread/644b63ab/

I also found a mention of the error message on StackOverflow, where it was apparently related to different time baselines and lack of udunits support, but I checked and both of those are not the case here.

I'm using NCO version 5.1.9 on NCAR's casper system.

(Obviously, I can just ignore the warning, since it's non-fatal, but it does make it harder to filter through logfiles to detect actual problems when operating on very large datasets, so I wanted to report the problem.)  Thanks!

**Comment by czender** [comment]
Hi Seth, Thanks for your report. I can reproduce the problem with the latest version of NCO. The WARNING is annoying and incorrect and I will try to fix it. I'll post again when I've made progress.
CZ

**Comment by czender** [comment]
The latest snapshot has the fix that solves the problem for reproducer I created. If you can build/test snapshots, please do and LMK how it works for you. Otherwise this fix will appear within a month in NCO 5.3.1.

**Comment by sethmcg** [comment]
Awesome!  I have no ability to build snapshots, but I look forward to having the fix next release.

Thanks a bunch!

**Comment by czender** [comment]
My pleasure!
