### ISSUE TITLE
Packaging NCO in Spack

### ISSUE THREAD

**Issue by adamjstewart** [nco/nco#42]
I'm a developer for the [Spack](https://github.com/LLNL/spack) package manager. We had a [preliminary package for NCO](https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/nco/package.py), but it didn't have a lot of the fancier features. I'm trying to [update our package](https://github.com/LLNL/spack/pull/2639) to support things like openmp, dap, and esmf, but I have a few remaining questions:

1. For the DAP dependency, does NCO directly link to DAP, or does it pick it up from NetCDF? Also, is curl fine or should I use opendap or libdap? 

2. For the OpenMP support, is it smart enough to not use openmp when I try building with Clang or should I explicitly disable that? 

3. What is necessary for ESMF support?

4. Does NCO require flex and bison? I notice it is looking for them during configure. Does the build crash or do anything differently if they are not found? 

5. I tried running `make -j16 check` but it looks like it's hanging. The last thing it prints is: 
``` 
cd bm && ./nco_bm.pl --regress 

INFO: Testing for required modules 

Ooops! Time::HiRes (needed for accurate timing) not found 
Continuing without timing. IO::Socket ... found. 
``` 

Any idea what is going wrong with the tests? Or does it just take a long time with no output?

**Comment by czender** [comment]
I'll copy my previous replies below. Seems like you may not have received some of them:

> 1. For the DAP dependency, does NCO directly link to DAP, or does it
> pick it up from NetCDF? Also, is curl fine or should I use libdap?

NCO gets DAP from libnetcdf, and CURL from libcurl.
libdap is not necessary.

> 2. For the OpenMP support, is it smart enough to not use openmp when I
> try building with Clang or should I explicitly disable that?

It's smart enough (I think). The configure works
fine for me on MacOS/clang and gcc.

> 3. For the ESMF support, what do you mean by it not linking to ESMF? Is
> ESMF something that I should install after NCO, or is it something that
> is picked up during configure if available? What does --enable-esmf
> actually do?

Install ESMF after NCO.
This will support off-line regridding by ncremap.
--enable-esmf will, when it works, enable integrated
(rather than off-line) regridding.

> 4. Does NCO require flex and bison? I notice it is looking for them
> during configure. Does the build crash or do anything differently if
> they are not found?

Yes, it requires both flex and bison.

> 5. I tried running `make -j16 check` but it looks like it's hanging. The
> last thing it prints is:
> ```
> cd bm && ./nco_bm.pl --regress
>
> INFO: Testing for required modules
>
> Ooops! Time::HiRes (needed for accurate timing) not found
> Continuing without timing. IO::Socket ... found.
> ```
>
> Any idea what is going wrong with the tests? Or does it just take a long
> time with no output?

I'm not quite sure. That works for me.
Try installing all the Perl
modules it needs. Try without -j 16. NB: Once
all dependencies are installed, there will still
be some (~10) test failures. This is normal/expected.

**Comment by adamjstewart** [comment]
Thanks @czender, your email must have never gone through for some reason.

I just built NCO 4.6.3 on Blues. I think it has everything you want. Can you test it out for me? The soft key is `+nco-4.6.3`. The output of the build can be found in `/soft/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-6.1.0/nco-4.6.3-a22k7jebhbaoq5s5hfmlzkednwho625e/.spack/build.out`. I think I may need to explicitly `--enable-esmf` for it to work, so I'll try another build.

**Comment by czender** [comment]
Do not use --enable_esmf. Ever. Period. Fuggetaboutit. It refers to _linking_ the ESMF library to the NCO library and it is not documented or supported.

This is distinct from, and consistent with, the benefits of installing the ESMF command line executables for NCO to use. Aside from that it appears to me that your build of NCO 4.6.3 works perfectly. Good job! This will be very helpful for NCO users at other spack sites like ALCF (if you could ask someone to use your spack package to update NCO on cooley/mira that would be great).

Unless I am mistaken, the last desired feature is to install ESMF executables. Usually they come with NCL, but, I just checked, apparently your spack ncl does not come with ESMF. What it boils down to is that NCO occasionally wants to call the ESMF_RegridWeightGen executable. Please find a way to provide that capability, either by adding it to your ncl spack package, or your nco spack package, or as a new "esmf" spack package that the nco package will automatically load.

**Comment by adamjstewart** [comment]
Will do!

**Comment by adamjstewart** [comment]
> Please find a way to provide that capability, either by adding it to your ncl spack package, or your nco spack package, or as a new "esmf" spack package that the nco package will automatically load.

I'm still not sure if I understand what ESMF is. Is it a command line program that can be downloaded and installed on it's own, or can NCO or NCL build it themselves? Is this the correct [homepage](https://www.earthsystemcog.org/projects/esmf/)?

**Comment by czender** [comment]
ESMF is the name of the overall package that includes ESMF_RegridWeightGen, the executable that is the only part of ESMF that NCO cares about. ESMF is usually, though not always, built as part of the NCL package. I'm not sure why your NCL did not get built with it. Yes, that is the correct ESMF homepage.

**Comment by adamjstewart** [comment]
ESMF has turned out to be harder than I expected to package. It doesn't use a standard build system like Autotools or CMake, it relies entirely on environment variables. It also doesn't seem to be playing nicely with Spack's compiler wrappers, and the RPATH isn't being set properly. It may take longer than I expected to get ESMF installed and working correctly at LCRC.

In the meantime, I'm going to close this Issue as it isn't really an issue with NCO itself. Thanks for your guidance!
