### ISSUE TITLE
Netcdf requirements missing

### ISSUE THREAD

**Issue by ppoilbarbe** [nco/nco#44]
It would be nice to put in INSTALL file or to check in configure the needed version of netCDF library.
I tried to build NCO 4.6.3 on Ubuntu XENIAL (netCDF C 4.4.0 installed by package) where netcdf_mem.h is missing (and nc_open_mem function). configure passed but make failed.
Maybe it would be the same thing with other libraries.
After trying 4.6.2 which had the same issue,  I switched to 4.6.1 which does not seem to use in memory files.

**Comment by czender** [comment]
Thanks for this report. According to my information, netCDF 4.4.0 is supposed to include the netcdf_mem.h header and the token NC_LIB_VERSION in netcdf.h should have the value 440. NCO depends on these assumptions. I don't have the resources to track down this information for every distribution. If either assumption is wrong (for Ubuntu) please let me know, and be specific, and we'll alter the configure.ac file to do the right thing.

**Comment by ppoilbarbe** [comment]
Sorry, its my fault: I did not dig enough into the code of netCDF.
Ubuntu netCDF packages are made using cmake not the autotools. The problem comes from here.
I just have done a build with both tools and the main differences are: cmake does not include the netcdf_mem.h nor the static library.
As I am not authorized to do a local build of the netCDF package I must rely on the one furnished with the distribution... :( 
So you can close this issue, it's not from CDO but from netCDF.

**Comment by czender** [comment]
Interesting. Now we know. Closing this issue.
