### ISSUE TITLE
Performance issues with Increasingly record chunk size

### ISSUE THREAD

**Issue by ocehugo** [nco/nco#46]
Hi,

I'm facing a performance problem with ncrcat with large files and chunking.

I can get a "standard" performance doing the following:

```ncrcat -D9 -4 -L1 --cnk_plc=g3d --cnk_dmn=time,1 --cnk_dmn=lat,1500 --cnk_dmn=lon,1500 `ls *.nc` test.nc```

for this case nco is a rather quick. My individual files are nc6 (~150mb each/no chunking) with size  1x6000x7000.

but when i tried to increase the time chunk:

```ncrcat -D9 -4 -L1 --cnk_plc=g3d --cnk_dmn=time,360 --cnk_dmn=lat,1500 --cnk_dmn=lon,1500 `ls *.nc` test.nc ``` 

I get runtimes much slower and nco is taking much more time to process each individual file. 
Example:
Using time chunks of 1,5 and 10 cause runtimes of about 6s, 20s, 50s for 10 individual files (1.6gb). All files were already cached in these tests and were lying in tmpfs locations (both input and output).

If I keep increasing the time chunksize beyond the number of files (say I have the same 10 as above) the speed is more problematic: ``` ncrcat -D9 -4 -L1 --cnk_plc=g3d --cnk_dmn=time,100 ...``` generate runtimes of the order 100s. So it's clear that the time chunking is affecting performance when reading individual files/arrays. This get worse when using large classical time chunks dimensions (like 365 , 1460, 2920).

Is this expected? 

I can feel a memory access pattern problem but i would like to have the best performance without flipping the dimensions and avoid using nonrecord files. A coffee would also be good...

Currently my aggregations are taking a long time and it's clearly bounded by cpu (several parallel calls are consistently slow and reading/writing at about the same speed). The case is a classical aggregation - individual daily files of a year chunked in time for half a year. The chunks are about  180x1000x1000 from the full variable 365x6000x7000 and again from nc6 files. They were originally N4L1 files with chunking and the ncrcat call were also doing a subset, but I dumb down to full nc6 files to check if it was a reading problem when dealing with chunking/cutting.

**Comment by czender** [comment]
Chunking performance is, to me, largely a mystery. 
It is all handled "under-the-hood" in the netCDF4-HDF layer.
We recently implemented the --cnk_csh switch to set the size of the per-variable-chunk cache.
You might try that.
I guess I don't understand why you don't just run with the fastest chunking you can find, i.e., time=1. I suppose it's because you want faster access to "pencils" of time in the output file.
Please read http://www.unidata.ucar.edu/blogs/developer/en/entry/chunking_data_why_it_matters
http://www.unidata.ucar.edu/blogs/developer/en/entry/chunking_data_choosing_shapes

**Comment by ocehugo** [comment]
@czender ,

I can't really tested `--cnk_csh` since it's only on ncks. The option is not available in ncrcat. 

and yes, i want to exactly perform faster readings over the time dimensions. It's a time/fft/ssa analysis in a large dataset and reading performance with time chunks of 1 is pretty bad.

**Comment by czender** [comment]
I just committed a change to the latest snapshot that enables --cnk_csh
on ncra, ncea, ncrcat. It works the same way the ncks option works.
Please post whether it helps your use case.

**Comment by ocehugo** [comment]
Hi zender,

thanks for the following up. Yes increasing the cache now makes things much more faster and I can reproduce the slowness with a smaller cache input! Thanks! TI did a push request since the option was not fully implemented ( missing some definitions and argument reading in ncra.c).

**Comment by czender** [comment]
The chunk cache option --cnk_csh is now in all NCO operators and will be released with 4.6.5. Glad it helps with your use-case. Closing this issue.
