### ISSUE TITLE
ncks flags

### ISSUE THREAD

**Issue by FlyingWithJerome** [nco/nco#50]
@czender 
In order to double check, here is the list of ncks flags (i.e., the argument that does not need to be in / cannot be in key-value pair) I summarized from the ncks documentation.

| description          |       flag(s)    |
|----------------------|-----------------|
|Do not alphabetize extracted fields | --abc, --alphabetize|
|Print human-legible calendar strings| --cal --calendar, --cln, prn_lgb|
|Print hidden attributes| --hdn, --hidden|
|Print as valid CDL| --cdl|
|Print as JSON| --jsn, --json|
|Turn on/off copy global/group metadata| --Mtd, --Metadata|
|Turn on/off copy variable metadata| --mtd, --metadata|
|Print numeric representation of missing values| --no_blank, --noblank, --no-blank|
|Print data, metadata and units| --print, --prn|
|Quench all printing to the screen| --quench|
|Retain all dimensions| --rad, --retain_all_dimensions, --orphan_dimensions, --rph_dmn|
|Print summary of ncks hidden features| --secret, --ssh, --scr|
|Toggle the printing of a variable’s units attribute| --units|
|Print as XML in NcML| --xml, --ncml, (additional: --xml_no_location, --xml_spr_chr, --xml_spr_nmr)|

If there's no interface like
```c
int nco_is_flag(char* flag);
```
I will try to hard-code them into the source file so that the NCO can clearly recognize the flags and invalid keys (the keys without values).

The list above only includes the long argument.
I would also like to know how a flag is passed to the NCO processor, also by a key-value structure but with a NULL value?

**Comment by czender** [comment]
i'm glad you checked-in on this. please do not modify ncks.c. the task is to modify the multi-argument (MTA) code that you already wrote. and that is initialized in the rgr, sld, trr routines. we need that routine to handle flags. ncks already does (because getopt() does). but your MTA does not. the hard-coded flags will mostly be for rgr so that nco_rgr_ini() can do the right thing. any hardcoded flags should go there or in the MTA source code.

**Comment by FlyingWithJerome** [comment]
I'm thinking on this way as well. I just read through the [ncks.c](https://github.com/nco/nco/blob/master/src/nco/ncks.c) and saw that these flags had already been hardcoded in
```c
static struct option opt_lng[];
```
Unfortunately it is static and in main().

Also, seems NCO has different streams of processing on key-value pairs and flags. The flags had already been picked up by ncks way before the nco_rgr_ini() is called (at the very beginning of the huge infinite loop). If the flags come with rgr,  trr or gaa key-value pairs, then where should we pass them to?

**Comment by czender** [comment]
Yes, NCO has two levels of input processing. Do not concern yourself with the ncks.c front end. The task for you is to allow MTA to parse flags. Put a hard-coded list of flags either in nco_arg_mlt_prs() or in a calling routine like nco_rgr_ini(), whichever seems more elegant/maintainable/extensible.

**Comment by FlyingWithJerome** [comment]
@czender 
I mean I'm curious about how to pass the flags, since the flags had already been parsed before nco_rgr_ini() is called in the main loop.
Or the flags can be passed like a key-value pair but with a NULL value?

**Comment by czender** [comment]
everything will still be passed through rgr_arg into nco_rgr_ini(). ncks.c does not need to be modified. period. trace the code to see what happens now with --rgr arguments.

**Comment by FlyingWithJerome** [comment]
@czender 
It may take some extra time since both Valgrind and gdb are down on my Mac due to the OS version. Rebuilding with other versions also failed; it is catastrophic. I need to squeeze my disk so that I can have enough space to set up a Linux virtual machine as a new environment

**Comment by FlyingWithJerome** [comment]
@czender 
Here is the list of the rgr/gaa/trr/ppc flags I concluded from the source code. No gaa/ppc/trr flags so far. I will hard code these flags to nco_mta.c so that in the future we can have a place to add/remove and keep track on these flags.

| flag               | gaa/trr/ppc/rgr |
| ------------------ | --------------- |
| --no_area          | rgr             |
| --no_area_out      | rgr             |
| --cell_measures    | rgr             |
| --cll_msr          | rgr             |
| --no_cell_measures | rgr             |
| --no_cll_msr       | rgr             |
| --curvilinear      | rgr             |
| --crv              | rgr             |
| --infer            | rgr             |
| --nfr              | rgr             |
| --no_stagger       | rgr             |
| --no_stg           | rgr             |

**Comment by czender** [comment]
This patch is in an working in 4.6.7
