### ISSUE TITLE
Can not convert file with a '_Netcdf4Dimid` attribute to NetCDF4

### ISSUE THREAD

**Issue by kwilcox** [nco/nco#57]
If there is a `_Netcdf4Dimid` attribute on any variable, `ncks` will error when trying to convert to NetCDF4 (`-4` or `-7`).

### Reproduce:

**No workie**
```
$ ncks -O -v z http://oceanmodeling.pmc.ucsc.edu:8080/thredds/dodsC/ccsra_2016a_phys_agg_zlevs/fmrc/CCSRA_2016a_Phys_ROMS_z-level_\(depth\)_Aggregation_best.ncd out.nc
$ ncks -O -7 out.nc out.nc
nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco_copy_att()
nco_err_exit(): ERROR Error code is -42. Translation into English with nc_strerror(-42) is "NetCDF: String match to name in use"
nco_err_exit(): ERROR NCO will now exit with system call exit(EXIT_FAILURE)
```

**Workie**
```
$ ncks -O -v z http://oceanmodeling.pmc.ucsc.edu:8080/thredds/dodsC/ccsra_2016a_phys_agg_zlevs/fmrc/CCSRA_2016a_Phys_ROMS_z-level_\(depth\)_Aggregation_best.ncd out.nc
$ ncatted -h -O -a _Netcdf4Dimid,,d,, out.nc out.nc
$ ncks -O -7 out.nc out.nc
```

**Comment by kwilcox** [comment]
Errors on both `4.6.1` and `4.6.7`

**Comment by czender** [comment]
@kwilcox While I appreciate learning about this circumstance and its workaround, NCO cannot solve the root of the problem. _Netcdf4Dimid is, apparently, a fragile and poorly documented netcdf-Java kludge for HDF. NCO uses only the netCDF API and never directly manipulates "system" attributes like _Netcdf4Dimid.  BTW, nccopy is the same way, and also fails on this file. Please file this bug report directly with Unidata.
