### ISSUE TITLE
ANTLR download missing

### ISSUE THREAD

**Issue by adamjstewart** [nco/nco#58]
It looks like the patched version of ANTLR 2.7.7 (http://dust.ess.uci.edu/tmp/antlr-2.7.7.tar.gz) needed to build NCO is no longer available for download. Does anyone have a patch I can add to the Spack package for ANTLR?

**Comment by czender** [comment]
Sorry for the broken link. It is now restored. 
The preferred location is http://dust.ess.uci.edu/nco/antlr-2.7.7.tar.gz
and the /tmp location is now deprecated.

**Comment by zerothi** [comment]
This link is dead again ;)

Any change of moving away from antlr? :)

**Comment by czender** [comment]
Thank you for the note. I'm having webserver issues. For now you can grab this from

http://e3sm.ess.uci.edu/tmp/antlr-2.7.7.tar.gz

No, we're stuck with antlr2 until/unless a volunteer updates the parser to something more modern.
