### ISSUE TITLE
4.6.7 tar content has changed

### ISSUE THREAD

**Issue by iMichka** [nco/nco#59]
Hi. I am one of the homebrew package manager maintainers.

We pushed the 4.6.7 release to our users. Meanwhile the sha256 of the tar file has changed, meaning that the tag has been moved. This is pretty bad practice. We rely on the sha256 for security reasons, allowing to check if upstream is delivering something fishy. In general you may want to tag a new release instead of moving the tag, if you realise that your release had some major flaw.

Could you please confirm that the change was made on purpose? Also, how big is the difference between the two tags? Should we distribute this with a different version to our users to notify them that there was some change between 4.6.7 and 4.6.7.new ?

See https://github.com/Homebrew/homebrew-science/pull/5887 for reference.

**Comment by czender** [comment]
Confirmed. There was a short (few hour) window when the original 4.6.7 was pulled then modified to prevent a bug from being released. Your SHA256 is correct, and SHA256 values are now displayed on the NCO homepage. Sorry for the trouble, and thanks for packaging NCO for homebrew!
