### ISSUE TITLE
Unable to run "make" with 4.6.9

### ISSUE THREAD

**Issue by warrensmith108** [nco/nco#60]
I am attempting to install the 4.6.9 NCO libraries on a Red Hat Enterprise Linux desktop.  I already have the NetCDF4 libraries installed on my machine (installed to /usr/local) and I have tried setting the NETCDF_ROOT, NETCDF_INC, and NETCDF_LIB environment variables but I still get the following output when I try to run "make":

./.libs/libnco.so: undefined reference to `nc_get_chunk_cache'
./.libs/libnco.so: undefined reference to `nc_def_var_deflate'
./.libs/libnco.so: undefined reference to `nc_inq_ncid'
./.libs/libnco.so: undefined reference to `nc_inq_var_fletcher32'
./.libs/libnco.so: undefined reference to `nc_inq_grp_parent'
./.libs/libnco.so: undefined reference to `nc_inq_unlimdims'
./.libs/libnco.so: undefined reference to `nc_inq_grpname_len'
./.libs/libnco.so: undefined reference to `nc_inq_grps'
./.libs/libnco.so: undefined reference to `nc_def_var_chunking'
./.libs/libnco.so: undefined reference to `nc_inq_var_chunking'
./.libs/libnco.so: undefined reference to `nc_inq_var_deflate'
./.libs/libnco.so: undefined reference to `nc_inq_grp_ncid'
./.libs/libnco.so: undefined reference to `nc_inq_var_fill'
./.libs/libnco.so: undefined reference to `nc_def_var_fletcher32'
./.libs/libnco.so: undefined reference to `nc_inq_grpname'
./.libs/libnco.so: undefined reference to `nc_inq_grpname_full'
./.libs/libnco.so: undefined reference to `nc_def_grp'
./.libs/libnco.so: undefined reference to `nc_inq_dimids'
./.libs/libnco.so: undefined reference to `nc_set_chunk_cache'
./.libs/libnco.so: undefined reference to `nc_inq_grp_full_ncid'
./.libs/libnco.so: undefined reference to `nc_inq_varids'
./.libs/libnco.so: undefined reference to `nc_inq_var_endian'
./.libs/libnco.so: undefined reference to `nc_rename_grp'
collect2: error: ld returned 1 exit status
make[4]: *** [ncap] Error 1
make[4]: Leaving directory `/home/wsmith/Downloads/nco-4.6.9/src/nco'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/home/wsmith/Downloads/nco-4.6.9/src/nco'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/wsmith/Downloads/nco-4.6.9/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/wsmith/Downloads/nco-4.6.9'

./configure runs to completion and tells me I am ready to run "make," but nonetheless I still have this problem.  I am attaching config_log and my configure_output text as well.

Please let me know if you have any ideas for why this doesn't work.

[config_log.txt](https://github.com/nco/nco/files/1432432/config_log.txt)
[config_output.txt](https://github.com/nco/nco/files/1432433/config_output.txt)

Thank you!

Ren Smith

**Comment by czender** [comment]
I need to see the first "make" command that fails.

**Comment by warrensmith108** [comment]
Thanks for your fast response!  I am attaching the output from the make command.  At the end it terminates, stating that it can't find shared libraries (should be the same output that I copied above).

Thank you!

[make_out.txt](https://github.com/nco/nco/files/1434455/make_out.txt)

**Comment by czender** [comment]
It seems likely that the netCDF library in /usr/local/lib was built without netCDF4.
There is nothing NCO can do about that. Please re-build and re-install netCDF.

```
checking whether NC_CHUNKED is declared... yes
configure: netcdf.h contains netCDF4 definitions
checking for nc_def_var_chunking in -lnetcdf... no
configure: Bad news: Simple program does not compile and link with netCDF4 library
checking for gcc -std=gnu99 option to support OpenMP... -fopenmp

```
