### ISSUE TITLE
Feature request: ability to specify MPAS input file prefix to ncclimo

### ISSUE THREAD

**Issue by xylar** [nco/nco#67]
E3SM runs have a very specific format for the monthly mean output files from MPAS components (currently MPAS-O and MPAS-SeaIce, soon MPAS-LandIce).  When we do standalone runs, these files can have different names by default.  It isn't that hard for us to use the E3SM naming convention but sometimes we forget.

It would be nice to have a flag that would allow us to override the default file prefix (e.g. `mpaso.hist.am.timeSeriesStatsMonthly`) for MPAS input files.  It looks like there is a  `--fl_lst_in`, `--file_list` for some NCO commands, so might it be appropriate to have something like `--fl_pfx_in`, `--file_prefix_in` for ncclimo?  I'm not sure whether you would want to support this for all the different file formats supported by ncclimo or just for MPAS, I'd leave that up to you.

**Comment by xylar** [comment]
@pwolfram, this should eventually help with analyzing the simulations you presented today.  We can come up with an alternative fix in the meantime.

**Comment by czender** [comment]
Implementing `--fl_lst_in` is problematic (i.e., lots of code) though doable in `ncclimo`. Please read the documentation on  [caseid](http://nco.sf.net/nco.html#caseid) and this example workaround with [merra2](http://nco.sf.net/nco.html#merra2). If the MPAS models share a common numeric suffix we could make that work most easily. For example, `ncclimo -c` already understands arguments like `foo_YYYYMM.nc`. It knows how to isolate `foo`, use that as the caseid (i.e., filename prefix), and how to generate  the necessary YYYYMM suffixes for the rest of the files specified in the date range. Would something like that work for MPAS? e.g., would `foo_YYYY-MM-DD.nc` satisfy you? Or are the names just totally random with no consistent suffixes?

**Comment by xylar** [comment]
@czender, this is great!  I sounds like ncclimo already does what we would need without any changes needed.  Your example looks exactly like what we would want.  I'll try it out and make sure it works for our case but it looks very likely.

Sorry I had forgotten about the caseid option.  I'll close this issue as soon as I can confirm this takes care of us.

**Comment by pwolfram** [comment]
Thanks @xylar and @czender for taking a close look into this issue!

**Comment by xylar** [comment]
@czender, after @pwolfram and I struggled a little today to get me access to the data set we're testing on, I tried to create a climatology using `ncclimo` but no luck.

So the situation is that MPAS components can specify an arbitrary template for file names like:
```
filename_template="restarts/restart.AM.timeSeriesStatsMonthly.$Y-$M-$D_$h.$m.$s.nc"
```

In the particular case I was looking at, the format was:
```
filename_template="analysis_members/timeSeriesStatsMonthly.$Y-$M.nc"
```
but the dot and the hyphen are still not what `ncclimo` is expecting.

For MPAS-Analysis not to place restrictions on users that might want to use this formatting, we would like to support file names with these types of complicated template.  But it is clear that `ncclimo` has a relatively restricted format that is supported by the `--case` flag (a suffix of the form `YYYYMM.nc`).  Rather than making you extend `ncclimo` to suit our complicated case, it seems *much* easier to have MPAS-Analysis make symlinks to the files in a temporary directory using the E3SM standard formatting for file names.  Then, `ncclimo` can proceed as normal.

Thanks for indulging me.

**Comment by czender** [comment]
@xylar and @pwolfram that's fine. Though to me it seems more complex to generate a directory with symbolic links prior to running `ncclimo`. The beta3rc13 run on edison includes these outputs:
```
mpaso.hist.am.globalStats.0334-10-01.nc
mpaso.hist.am.layerVolumeWeightedAverage.0334-10-01.nc
mpaso.hist.am.meridionalHeatTransport.0334-10-01.nc
mpaso.hist.am.mixedLayerDepths.0334-10-01.nc
mpaso.hist.am.surfaceAreaWeightedAverages.0334-10-01.nc
mpaso.hist.am.timeSeriesStatsMonthly.0334-10-01.nc
```
The regular expression (rx) `foo.YYYY-MM-01.nc` supports these six cases reasonably well. So I just added that rx to `ncclimo`. You can use `--fml_nm` to change the output names to something clearer, e.g., `--fml_nm='deck'`. This is all in 4.7.3-alpha03 which is now on edison to play with. Commands with the new rx patterns should work, e.g., 

`
drc_in=/global/cscratch1/sd/golaz/ACME_simulations/20171228.beta3rc13_1850.ne30_oECv3_ICG.edison/archive/ocn/hist
ncclimo -d 1 -a sdd -v timeMonthly_avg_latentHeatFlux -s 0300 -e 0300 --caseid=mpaso.hist.am.timeSeriesStatsMonthly.0334-10-01.nc -r ${DATA}/maps/map_oEC60to30v3_to_fv257x512_bilin.20180301.nc --drc_in=${drc_in} --drc_out=${DATA}/mpas/clm
`
It's not a big deal to add new rx's so do not hesitate to ask.

**Comment by xylar** [comment]
@czender, I think this approach would work well for us.  Thanks very much!  There's one more expression we would typically want to support and that would be `foo.YYYY-MM.nc`.  That, together with `foo.YYYY-MM-01.nc` would be the only likely file naming conventions I could think of.  Would that be easy to add?

**Comment by czender** [comment]
Yes, done, you can try it out with the `ncclimo` in `~zender/bin_edison`.

**Comment by xylar** [comment]
Thanks! 

I just tried it out with the following command:
```
ncclimo -d 1 -a sdd -v timeMonthly_avg_latentHeatFlux -s 0001 -e 0001 --caseid=timeSeriesStatsMonthly.0001-01.nc --drc_in=. --drc_out=clim

```
and I get an error:
```
Climatology operations invoked with command:
/global/homes/z/zender/bin_edison/ncclimo -d 1 -a sdd -v timeMonthly_avg_latentHeatFlux -s 0001 -e 0001 --caseid=timeSeriesStatsMonthly.0001-01.nc --drc_in=. --drc_out=clim
Started climatology generation for dataset timeSeriesStatsMonthly.0001-01.nc at Sat Feb  3 19:38:57 PST 2018
Running climatology script ncclimo from directory /global/u1/z/zender/bin_edison
NCO binaries version 4.7.3-alpha03 from directory /global/u1/z/zender/bin_edison
Producing standard climatology from raw input files in directory .
Output files to directory clim
Climatology from 1 years of contiguous raw data touching 1 calendar years from YYYYMM = 000101 to 000112
Filenames will be constructed with generic conventions as .YYYY-MM.
Each input file assumed to contain mean of one month
Winter statistics based on seasonally discontiguous December (sdd-mode): DJF sequences comprise three months from the same calendar year
Annotation for CF climatology attribute and climatology_bounds variable will be performed
This climatology will not be regridded
ncclimo: ERROR Unable to find required input file ./.000101.
ncclimo: HINT All files implied to exist by the climatology bounds (start/end year/month) must be in . before ncclimo will proceed
```
It looks like it's dropping the parts of the filename before and after the dot.  Any idea why that might be happening?

**Comment by czender** [comment]
I left the door open and cookies out so bugs crawled in. Now fixed.

**Comment by xylar** [comment]
Yep, seems to work great now.  Thanks again!
