### ISSUE TITLE
NCO organization and Python bindings to NCO

### ISSUE THREAD

**Issue by jhamman** [nco/nco#7]
Hi Charlie - 

First off, its great that you've moved `nco` over to Github.  I think this is great.

As I think you already know, I've developed [Python bindings to NCO](https://github.com/jhamman/nco-bindings).  I'm wondering if you would be interested in creating a "Github Organization" to house the `nco` and `nco-bindings` repositories (and others that seem fitting).  Similar organizations may be [Unidata](https://github.com/Unidata) or  [Pydata](https://github.com/pydata)? I'm happy to continue to contribute to the development of the Python bindings, but I get the feeling the larger user community may be more likely to contribute to both packages if they are outside of my Github domain.  

Just a few thought, no worries if you don't like the idea.  

Cheers,

Joe

**Comment by czender** [comment]
Hi Joe,

Thanks for this suggestion. I can't think of any reason _not_ to make an NCO organization. I've been using Git for a few months now and I like it. I've created one other organization, and people are now beginning to use it. If no unpleasant issues crop-up, then I'll be happy to do the same with NCO. I intend to look more carefully at your Python bindings this summer, regardless, and having everything in one organization might make that easier. Feel free to ping me in a month if I havn't made the change yet.

Charlie

**Comment by jhamman** [comment]
Sounds good Charlie.  Let me know if you have any questions about the Python bindings.

Joe

**Comment by jhamman** [comment]
@czender - just a ping to see where you're at with this.  Cheers.

**Comment by czender** [comment]
what do you suggest for an organization name?
i just checked and NCO and nco are already taken
-- 
Charlie Zender, Earth System Sci. & Computer Sci.
University of California, Irvine 949-891-2429 )'(

**Comment by jhamman** [comment]
Bummer.  I'm typically terrible at these sorts of things.

`ncops`, `netcdf-tools`, `N-C-O`, `CAMDA`, `ClimData` or derivations of these are just a few off the top of my head.

**Comment by czender** [comment]
those seem kind of contrived. would you consider merging your bindings into the NCO repo itself?

**Comment by jhamman** [comment]
I'm not super keen on the idea, mostly because it would be difficult to distribute the python-bindings apart from the c sources. If we were to go this way, we should talk about installing the python-bindings at the same time as NCO.  I'm not sure exactly how we would do that - but we could work it out.

You may consider putting NCO in the [Unidata](https://github.com/Unidata) github organization.  @jswhit has done that with the [netcdf4-python](https://github.com/Unidata/netcdf4-python) and still maintains the principle development role. He may be able to comment further but it seems that it has increased the visibility of the project and encouraged other contributors.

cc: @ocefpaf, @kwilcox for any comments.

**Comment by ocefpaf** [comment]
> would you consider merging your bindings into the NCO repo itself?

Please don't!  That is every packager worst nightmare :stuck_out_tongue_winking_eye: 

Why not netcdf-operatos for the organization name?

**Comment by jhamman** [comment]
did you end up getting the nco user name: https://github.com/nco ?

**Comment by czender** [comment]
thanks for getting me to look at this site. i just checked and it appears that i registered "nco" about 4 years ago and never used it. it does appear to be my content. if i can get this name active as an organization then we can proceed as originally intended...

**Comment by czender** [comment]
as i mentioned offline, i was mistaken. i didn't register "nco" then forget, someone else registered it (and put an NCO image on the page). i asked GitHub to send that unknown person the following, and am waiting to hear back:

Hello GitHub user "nco",

I hope you are well. My name is Charlie Zender and I am the author and
maintainer of the netCDF Operator (NCO) software suite. A few months
ago the authors of other NCO-related software (python wrappers for
NCO, and the Debian and Fedora NCO maintainers) and I agreed to place
our NCO-related software under the same GitHub organization. We would
like to use the "nco" name for this, and hope you will allow GitHub to
transfer the "nco" username to me for that purpose.

NCO is free software written by and given to students, scientists, and
researchers involved in geophysics and global change research.
We would greatly appreciate the enhanced identity that the "nco" organization name would provide to our efforts.
Your generosity in  transferring this name would be greatly appreciated.
Please contact me personally at zender@uci.edu or 949 891-2429 if you
would like to discuss this.

Thank you for your consideration,
Charlie

**Comment by nco** [comment]
Joe, the "nco" registrar cooperated and gave me the username "nco". Am now trying to obtain "NCO" too, as that (all caps) may make a better organization name. Unsure how that will turn out, but will try to create the organization soon. Any tips/preferences on how to do that?

**Comment by jhamman** [comment]
I don't think the names are case sensitive so we can call the organization NCO rather than nco.

Once you have the organization setup, if you add me as a contributor/member, I'll transfer the ownership of the nco bindings to the organization. I'm happy to remain the principle maintainer of the repository for now.

**Comment by czender** [comment]
Done. Would appreciate some advice on how to move NCO from czender/nco to nco/nco. You seem to understand Git(Hub) better than I do. What is a good migration plan?

**Comment by jhamman** [comment]
From the settings menu in this repository, choose `Transfer ownership`. That will move your repo over to the nco organization.  Then, you can fork the nco repo to your own username. More docs here: https://help.github.com/articles/transferring-a-repository/

**Comment by jhamman** [comment]
@czender - This all looks good.  Thanks for going this way, I think it will serve you well. I'm going to close this now.

**Comment by czender** [comment]
@jhamman why would I fork the NCO repo to my own username as you suggest above? is that what you do for the wrappers? All I have done is 
git remote set-url origin https://github.com/nco/nco.git

**Comment by jhamman** [comment]
Yeah, a typical (but not mandatory) workflow for projects with multiple contributors is to not push directly to the central repository.  All the contributors push to their own forks and issue pull requests to the central repo.  This allows for code reviews and discussions in the pull requests and avoids merge conflicts in the central repo.

I've followed this workflow with `pynco`:

*Fork the nco/pynco repo*
```
git clone git@github.com:jhamman/pynco.git
cd pynco
git remote add upstream git@github.com:nco/pynco.git
git checkout -b my_feature/branch
```

*make changes to source code*

```
git add some files
git commit
git push origin
```
*Issue Pull Request from my fork to nco/pynco*
*Code review before merging pull request*
