### ISSUE TITLE
Deprecate ncap

### ISSUE THREAD

**Issue by czender** [nco/nco#71]
Please take some time to deprecate ncap (i.e., ncap1) from NCO.
That means eliminate it from autoconf and CMake build engines.
Then you will be an expert at autoconf and CMake
Be careful to retain the flex scanner for ncwa!
Please do and test this all on a branch not on master
and ask for a review and PR when ready.

I will eliminate ncap from bld/Makefile.

**Comment by czender** [comment]
The remaining files are ncap_lex.l, ncap_utl.h, ncap_utl.c

**Comment by hmb1** [comment]
Charlie and Pedro
have done the pull request and  done configure/make and cmake/make and everything is working for me. 
please report any  problems here

**Comment by czender** [comment]
Merged and will be in 4.7.3
