### ISSUE TITLE
ncap deprecation broke my build

### ISSUE THREAD

**Issue by czender** [nco/nco#76]
I tried to explain yesterday that the deprecation PR was not to be done until my mods were merged, and that those would be forthcoming once the mods from @hmb1 passed all tests. Not only did you execute the PR without waiting, but master no longer builds for me:

```
gcc -DHAVE_CONFIG_H -I. -I../..   -I/opt/local/include -I/opt/local/include  -I/opt/local/include -I/opt/local/include -I/opt/local/include/udunits2  -fno-common   -std=c99 -D_BSD_SOURCE  -MT ncap_lex.o -MD -MP -MF .deps/ncap_lex.Tpo -c -o ncap_lex.o ncap_lex.c
ncap_lex.l:59:10: fatal error: 'ncap.h' file not found
#include "ncap.h" /* netCDF arithmetic processor-specific definitions (symbol table, ...) */
         ^~~~~~~~
1 error generated.
gmake: *** [Makefile:1039: ncap_lex.o] Error 1

```
Please fix ASAP!

**Comment by czender** [comment]
The fix was to manually delete ncap_lex.c so that it would be rebuilt.

**Comment by hmb1** [comment]
Hi Charlie,
i did a fresh clone of the repo on  skyglow   and everything compiled OK 
I just need to remove ncap.c again  ( i had to "update" it to make the PR work )

Sorry I did the PR on master I should have updated the hmb-dep-ncap with the latest commits from master and left it at that
Going forward:  I assume this is how you wish to operate, new-features in branch and final PR and review by you 
 
...Henry

**Comment by czender** [comment]
Sorry for snapping at you. I thought I would have to revert the whole merge at first but I figured out it was a small issue.

Yes, we should have kept adding commits to the hmb-dep-ncap branch until is was complete, and included my bld/Makefile mods. 

Going forward I want all new major features/changes to pass all checks on a PR that I have seen and approved before the originator does the merge. Minor changes should be committed straight to master as usual.
