### ISSUE TITLE
Follow all draft CF2 Group scoping rules

### ISSUE THREAD

**Issue by czender** [nco/nco#79]
There is only one CF2 scoping rule to my knowledge that NCO does not yet follow, and it is somewhat of a corner case, yet NCO should handle it correctly. The CF2 Group draft [proposal](https://docs.google.com/document/d/1KK6IZ2ZmpaUTVgrw-GlFd6almppjvGz6D7nxVTO3BtI/edit) states:

> An identifier specified with a relative path (i.e., with an internal but no leading slash "/") resolves to the indicated location.  For example, a coordinates attribute of `g1/lat` refers to the `lat` variable in subgroup `g1` of the current (referring) group. Upward path traversals from the current group are indicated with the UNIX convention. For example, `../g1/lat` refers to the lat variable in the sibling group `g1` of the current (referring) group.

Please implement this procedure so that "`../`" is interpreted as the parent group and "`./`" is interpreted as the current group, and add regression test(s) to verify compliance.

**Comment by hmb1** [comment]
dos this take priority over chunking bm,s  ?

**Comment by czender** [comment]
Yes, I changed priority to high to make this clear.

**Comment by hmb1** [comment]
Have made  relevant mods to code and added new ncks regression test.
note the subtle distinction between 

**lat:bounds("new_bounds")**
and
**lat:bounds("./new_bounds")** 

The former means look in current group and if not found look  up the group hierarchy.
While the later means just look in  the current group.

**Comment by czender** [comment]
Yes, that is exactly what those two cases should do. Thanks.
