### ISSUE TITLE
ncap2 where() behavior

### ISSUE THREAD

**Issue by czender** [nco/nco#80]
This [question](https://sourceforge.net/p/nco/discussion/9830/thread/be317e77/?limit=25) occurs a lot. Please clarify this in the manual, provide a workaround example, and perhaps change ncap2 to die with an informative HINT when people attempt subscripting within where(). Otherwise they could inadvertently use the incorrect answers ncap2 currently produces in these situtations.

**Comment by hmb1** [comment]
@czender 
please review and close

**Comment by czender** [comment]
Looks good!
