### ISSUE TITLE
AppVeyor build broke

### ISSUE THREAD

**Issue by czender** [nco/nco#81]
Broke on build 1.0.239 on 3/13. Details in the AppVeyor [logs](https://ci.appveyor.com/project/czender/nco/history). The actual breakage appears unrelated to NCO:
```
conda.exe list
CondaEnvironmentNotFoundError: Could not find environment: C:\Miniconda36-x64\envs\base .
You can list all discoverable environments with `conda info --envs`.
```
@pedro-vicente do you have any ideas?

**Comment by ocefpaf** [comment]
I think the reason is an AppVeyor update. I'll try to send a PR fixing that soon.
