### ISSUE TITLE
Add optional scale_factor/add_offset arguments to ncap2 packing routine

### ISSUE THREAD

**Issue by czender** [nco/nco#88]
Please make scale_factor and add_offset optional arguments to the ncap2 pack() method, so users can specify these parameters as per discussion in:

https://sourceforge.net/p/nco/discussion/9829/thread/2bd55075/?limit=25#f65b

**Comment by hmb1** [comment]
Hi Charlie, 
have done the requested mods 
 Will add a regression test -   once  the existing regression tests have been fixed

**Comment by hmb1** [comment]
@czender 
Have fixed code in ncoGrammar -   scale_factor & add_offset attributes are now being written   when code is parsed twice.
ncap2 pack regression test is now working

**Comment by czender** [comment]
Is the thing where it only worked for three variables at a time fixed? Can we close this?

**Comment by hmb1** [comment]
yes
