### ISSUE TITLE
Error with Hyperslabs on the Right Hand Side of an assign

### ISSUE THREAD

**Issue by neumannd** [nco/nco#90]
Hey, I possibly encountered a minor issue with ncap2. I attached files to reproduce the issue ([issue_right_hand_hyperslabs.zip](https://github.com/nco/nco/files/2013920/issue_right_hand_hyperslabs.zip)). Cheers, Daniel

# Note

This issue arises with NCO 4.6.7 on openSUSE Leap 42.3 with netCDF 4.4.1.1 and HDF5 1.8.18. Unfortunately, I don't have the time to set up a more recent NCO version.

# Issue

I have got a netCDF file of the following structure (removed not-relevant parts):
```
netcdf grddat_test {
dimensions:
        depth = 36 ;
        lat = 347 ;
        lon = 414 ;
        time = UNLIMITED ; // (3 currently)
variables:
        double depth(depth) ;
                depth:units = "m" ;
                depth:standard_name = "depth" ;
                depth:long_name = "depth" ;
                depth:positive = "down" ;
        byte mask(time, depth, lat, lon) ;
                mask:long_name = "sea_binary_mask" ;
                mask:_FillValue = -1b ;
                mask:missing_value = -1b ;
}
```

If I apply the following scripts with `ncap2`

```
defdim("lev",$depth.size);
lev[$lev]=depth(:);
 sea_mask[$time,$lev,$lat,$lon]=mask(:,:,:,:);
```

it results in the error

```
copy_mask.nco:3:38: unexpected token: :
```

I attached a zip archive with the script and the netCDF file so that one can easily reproduce the issue.

[issue_right_hand_hyperslabs.zip](https://github.com/nco/nco/files/2013920/issue_right_hand_hyperslabs.zip)

# Why it should work

According to the manual this should work. In section _Hyperslabs on the Right Hand Side of an assign_ of the NCO manual it is written:
```
because the $lon dimension now only has two elements. The above can be calculated by using a LHS cast with $lon_nw as replacement dim for $lon:

defdim("lon_nw",2);
th_nw[$lat,$lon_nw]=th(0,:,0:1) +th(9,:,0:1);
```

**Comment by hmb1** [comment]
Hi there,
  'mask'  is a function in ncap2.  
  To get ncap2 to interpret it as a  variable simply quote (with single quotes)
  
   `sea_mask[$time,$lev,$lat,$lon]='mask'(:,:,:,:);`
    
   To see all the functions in ncap2 use the command-line:

   `ncap2 -f`

...Henry

**Comment by neumannd** [comment]
Hi Henry,
Ah ... . Thanks. Solves it. I should have tested it with other variable names ... :-) .
Daniel
