### ISSUE TITLE
missing cap.h?

### ISSUE THREAD

**Issue by BrianOBlanton** [nco/nco#93]
I think ncap.h is missing from src/nco in master.  I copied it from 4.6.1.

**Comment by czender** [comment]
ncap and ncap.h have been eliminated from NCO as of 4.7.3. You may need to do a fresh install (or `make distclean`) of the NCO sources to keep the build system from complaining.

**Comment by BrianOBlanton** [comment]
Ah. OK. Will do. Thx.


Cheers,

[/Users/bblanton/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1636295879]

Brian O. Blanton, Ph.D.
Director of Earth Data Sciences
Oceanographer
Renaissance Computing Institute
University of North Carolina at Chapel Hill
100 Europa Drive
Suite 540 Chapel Hill, NC, 27517

Brian_Blanton@Renci.Org<mailto:Brian_Blanton@Renci.Org>
919-445-9620 (O)

**Comment by BrianOBlanton** [comment]
yes. that did it. thanks again.
