### ISSUE TITLE
Regression tests for ncks --cal option

### ISSUE THREAD

**Issue by czender** [nco/nco#95]
Please add `regression tests to verify ncks --cal option` works, e.g., 
```
ncks --cal -v tm_365 ~/nco/data/in.nc
...
    tm_365 = 59; // calendar format: "2013-03-01"
...

```
Currently this option appears to be broken on my Mac

**Comment by czender** [comment]
This is currently the only high priority issue. Please commit a patch to master ASAP. The example in the first message above is incorrect. The --cal switch is just plain broken, and we don't have a regression test so we did not notice it.

```
zender@aerosol:~/data/ppr$ ncks --cal -v tm_365 ~/nco/data/in.nc
netcdf in {
  variables:
    double tm_365 ;
      tm_365:units = "days since 2013-01-01" ;
      tm_365:calendar = "365_day" ;

  data:
    tm_365 =  ;

} // group /
zender@aerosol:~/data/ppr$ 

```

**Comment by hmb1** [comment]
now fixed and in repo "master"

**Comment by hmb1** [comment]
@c
added ncks  regression test. 
Pls check and close

**Comment by czender** [comment]
Seems to work fine, closing
