### ISSUE TITLE
Regression tests to verify ncks --xml

### ISSUE THREAD

**Issue by czender** [nco/nco#96]
Please add regression tests to verify `ncks --xml` option works, e.g., 
```
zender@aerosol:~$ ncks --xml -v one ~/nco/data/in.nc
<?xml version="1.0" encoding="UTF-8"?>
<ncml:netcdf xmlns:ncml="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2" location="file:/Users/zender/nco/data/in.nc">
  <ncml:variable name="one" type="float" shape="">
    <ncml:attribute name="long_name" separator="*" value="one" />
    <values>1.</values>
  </ncml:variable>
</ncml:netcdf>

```

**Comment by hmb1** [comment]
@czender 
There is an issue with enum's as an attribute , there's only the "type"  xml-att to play with unlike a variable enum where you have "type" and "typedef" (which is defined as a string )

**Comment by hmb1** [comment]
@czender 
xmllint tests are now "validating" as oppose to just checking for "well-formed-ness"

**Comment by czender** [comment]
ncml-2.2 has no support for 64bit integer enums (enum8) either. I think we need NCO to generate the XML that a correctly formed schema would allow even if it violates ncml-2.2.  xmllint is clearly helpful at identifying such issues, and is a welcome addition to the regression tests.

**Comment by czender** [comment]
I changed this XML test to keep it from writing into a file named ": ".
