### ISSUE TITLE
Ability to add additional white-list characters through a CLI argument

### ISSUE THREAD

**Issue by kwilcox** [nco/nco#99]
I completely understand the need for the white-list feature in `4.7.3` but eventually I'll want to upgrade past `4.7.2` without specifying the `-D 73` workaround.

What about a way to specify additional white-list characters on the command line via a new argument available to all commands?

Example DAP endpoint that breaks (uses parenthesis) after white-list changes in `4.7.3`:
* http://oceanmodeling.pmc.ucsc.edu:8080/thredds/dodsC/ccsra_2016a_phys_agg_zlevs/fmrc/CCSRA_2016a_Phys_ROMS_z-level_(depth)_Aggregation_best.ncd

**Comment by czender** [comment]
Glad you knew about the workaround. Before I go down your suggested route, please let me know what other characters (besides parentheses) you think might be necessary for DAP. There is actually already a DAP-specific whitelist that is activated automatically on filenames that start with `dap4://` `http://` or `https://`:
`  static char wht_lst_dap[]="#=:[];|{}/<>";
`
Would adding parentheses to this satisfy your foreseeable needs?

**Comment by kwilcox** [comment]
Adding parenthesis to `wht_lst_dap` would solve my needs but I just realized I can url escape them and it works fine... so many no reason to update the whitelist.

This works:

```
ncks -c time,0,0 http://oceanmodeling.pmc.ucsc.edu:8080/thredds/dodsC/ccsra_2016a_phys_agg_zlevs/fmrc/CCSRA_2016a_Phys_ROMS_z-level_%28depth%29_Aggregation_best.ncd out.nc
```

**Comment by czender** [comment]
Yes, I think that's better than updating the whitelist. I should add that workaround to the manual...
